FROM node:18-slim

WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY server.js .
COPY public/ ./public/
COPY assets/ ./assets/

EXPOSE 3000

# Command will be overridden in docker-compose
CMD ["node", "server.js"]
